// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaceControl.Infraestrutura.Configuracao.Data;
using System;

namespace RaceControl.Infraestrutura.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Dominio.Entidades.Competidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<decimal>("TemperaturaMediaCorpo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Competidores");
                });

            modelBuilder.Entity("Dominio.Entidades.HistoricoCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CompetidorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCorrida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PistaCorridaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TempoGasto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CompetidorId");

                    b.HasIndex("PistaCorridaId");

                    b.ToTable("HistoricoCorrida");
                });

            modelBuilder.Entity("Dominio.Entidades.PistaCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("PistaCorrida");
                });

            modelBuilder.Entity("Dominio.Entidades.HistoricoCorrida", b =>
                {
                    b.HasOne("Dominio.Entidades.Competidor", "Competidor")
                        .WithMany()
                        .HasForeignKey("CompetidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.PistaCorrida", "PistaCorrida")
                        .WithMany()
                        .HasForeignKey("PistaCorridaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
