-- Table: public.Competidores

-- DROP TABLE IF EXISTS public."Competidores";

CREATE TABLE IF NOT EXISTS public."Competidores"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nome" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "Sexo" integer NOT NULL,
    "TemperaturaMediaCorpo" numeric NOT NULL,
    "Peso" numeric NOT NULL,
    "Altura" numeric NOT NULL,
    CONSTRAINT "PK_Competidores" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Competidores"
    OWNER to racecontrol;