-- Table: public.PistaCorrida

-- DROP TABLE IF EXISTS public."PistaCorrida";

CREATE TABLE IF NOT EXISTS public."PistaCorrida"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Descricao" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_PistaCorrida" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."PistaCorrida"
    OWNER to racecontrol;