-- Table: public.HistoricoCorrida

-- DROP TABLE IF EXISTS public."HistoricoCorrida";

CREATE TABLE IF NOT EXISTS public."HistoricoCorrida"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CompetidorId" integer NOT NULL,
    "PistaCorridaId" integer NOT NULL,
    "DataCorrida" timestamp without time zone NOT NULL,
    "TempoGasto" numeric NOT NULL,
    CONSTRAINT "PK_HistoricoCorrida" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HistoricoCorrida_Competidores_CompetidorId" FOREIGN KEY ("CompetidorId")
        REFERENCES public."Competidores" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_HistoricoCorrida_PistaCorrida_PistaCorridaId" FOREIGN KEY ("PistaCorridaId")
        REFERENCES public."PistaCorrida" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."HistoricoCorrida"
    OWNER to racecontrol;
-- Index: IX_HistoricoCorrida_CompetidorId

-- DROP INDEX IF EXISTS public."IX_HistoricoCorrida_CompetidorId";

CREATE INDEX IF NOT EXISTS "IX_HistoricoCorrida_CompetidorId"
    ON public."HistoricoCorrida" USING btree
    ("CompetidorId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_HistoricoCorrida_PistaCorridaId

-- DROP INDEX IF EXISTS public."IX_HistoricoCorrida_PistaCorridaId";

CREATE INDEX IF NOT EXISTS "IX_HistoricoCorrida_PistaCorridaId"
    ON public."HistoricoCorrida" USING btree
    ("PistaCorridaId" ASC NULLS LAST)
    TABLESPACE pg_default;